# Dockerfile
FROM docker.elastic.co/logstash/logstash:8.15.3

# Install required Logstash plugins
RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-opensearch logstash-output-opensearch

# Remove the default Logstash configuration
RUN rm -f /usr/share/logstash/pipeline/logstash.conf

# Copy custom pipeline and config files
COPY pipeline/ /usr/share/logstash/pipeline/
COPY settings/logstash.yml /usr/share/logstash/config/logstash.yml
